# PyTorch Tensor Basics
This notebook explains different kinds of tensors in PyTorch — scalars, vectors, matrices, and higher-dimensional tensors — along with basic operations.

In [40]:
import torch

## Scalar
A scalar is a single number (0-dimensional tensor).
1. Structure.ndim - gives the number of dimension the structure have.
2. Structure.item - converts the type of the structure back to the python int.

In [41]:
scalar=torch.tensor(7)
print(scalar)
print(scalar.ndim) #no. of dimention does scalar have
print(scalar.item()) #Get tensor back as python int

tensor(7)
0
7


## Vector (1D tensor)
1. Structure.shape - gives the structure size

In [3]:
vector=torch.tensor([6,9])
print(vector)
print(vector.ndim)
print(vector[1])
print(vector.shape)

tensor([6, 9])
1
tensor(9)
torch.Size([2])


## Matrix (2D tensor)

In [4]:
matrix=torch.tensor([[7,8],
                     [9,10]])
print(matrix)
print(matrix.ndim)
print(matrix[1])
print(matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
tensor([ 9, 10])
torch.Size([2, 2])


## Tensor (3D example)

![Screenshot2025-09-07031559.png](img/Screenshot2025-09-07031559.png)

In [42]:
tensor=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [10,11,12]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [10, 11, 12]]])
3
torch.Size([1, 3, 3])


![Screenshot2025-09-07025845.png](img\Screenshot2025-09-07025845.png)

## Random Tensor
Creating a Random Tensor of size --> rows=3 and columns=4.

In [6]:
random_tensor=torch.rand(size=(3,4))
print(random_tensor)
print(random_tensor.ndim)

tensor([[0.7600, 0.6760, 0.6687, 0.1841],
        [0.9924, 0.4575, 0.4638, 0.2396],
        [0.7088, 0.6454, 0.1453, 0.2459]])
2


## Random tensor shaped like an image (Height, Width, Channels)

In [7]:
random_image_size_tensor=torch.rand(size=(224,224,3))
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([224, 224, 3])
3


## Zeros and Ones

In [8]:
zeros=torch.zeros(size=(3,4))
print(zeros)
print(zeros*random_tensor)
ones=torch.ones(size=(3,4))
print(ones)
print(ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


## Creating ranges of tensors

In [9]:
zero_to_nine=torch.arange(0,10)
print(zero_to_nine)
one_to_ten=torch.arange(1,11)
print(one_to_ten)
one_to_thousand_with_50steps=torch.arange(start=1, end=1000, step=50)
print(one_to_thousand_with_50steps)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651,
        701, 751, 801, 851, 901, 951])


## Creating tensor-like another tensor

In [10]:
one_to_ten=torch.zeros_like(input=one_to_ten)
print(one_to_ten)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


## Tensor Datatypes and Devices
**NOTE:** tensor datatypes is one of the 3 big errors you'll run into with pytorch & deep learning 
1. tensor not right `datatype`
2. tensor not right `shape`
3. tensor not on the right `device`

In [11]:
float32_tensor=torch.tensor([3.0, 6.0, 9.0],
                            dtype=None, #what data type is the tensor (default=float32)
                            device=None, #what device is your tensor on (default=None=cpu)
                            requires_grad=False) #whether or not to track gradiants with this tensor operation
print(float32_tensor)
print(float32_tensor.dtype)
float16_tensor=torch.tensor([2.0, 4.0, 6.0],
                            dtype=torch.float16,
                            device="cuda",
                            requires_grad=False)
print(float16_tensor)
print(float16_tensor.dtype)

tensor([3., 6., 9.])
torch.float32
tensor([2., 4., 6.], device='cuda:0', dtype=torch.float16)
torch.float16


## Type conversion

In [12]:
float16_tensor=float32_tensor.type(torch.float16)
print(float16_tensor)
print(float16_tensor*float32_tensor)
int_32_tensor=torch.tensor([2,3,4], dtype=torch.int32)
print(int_32_tensor)
print(float32_tensor*int_32_tensor)

tensor([3., 6., 9.], dtype=torch.float16)
tensor([ 9., 36., 81.])
tensor([2, 3, 4], dtype=torch.int32)
tensor([ 6., 18., 36.])


## Checking tensor attributes

In [13]:
some_tensor=torch.rand(3, 4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.8742, 0.8960, 0.6023, 0.3208],
        [0.4637, 0.2618, 0.0885, 0.2671],
        [0.3340, 0.7274, 0.7381, 0.8906]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Basic tensor operations (Addition, Subtraction, Multiplication, Division)

In [14]:
tensor=torch.tensor([1,2,3])
print(tensor+10)
print(tensor-10) #SLOW
print(tensor*10)
print(tensor/10)
#OR
print(torch.add(tensor, 10))
print(torch.sub(tensor, 10)) #FAST
print(torch.mul(tensor, 10))
print(torch.div(tensor, 10))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


## Matrix Multiplication
**NOTE:** There are 2 types of matrix multiplication:
1. Element wise multiplication.
2. Matrix multiplication (dot product).

In [15]:
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")
print(torch.matmul(tensor, tensor))
#OR
print(tensor @ tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
tensor(14)
tensor(14)


## 2 Rules
There are `2 main` rules that performing matrix multiplication needs to satisfy:
### 1. Inner Dimension Should Match.
1. torch.Size([3, 2]) @ torch.Size([3, 4]) `won't work`.
2. torch.Size([3, 2]) @ torch.Size([2, 5]) `will work`.
3. torch.Size([2, 3]) @ torch.Size([3, 1]) `will work`.

**NOTE:** In matrix `A*B != B*A.`
### 2. The resulting matrix has the shape of the Outer Dimension.

In [16]:
matrixmul=torch.matmul(torch.rand(2,3), torch.rand(3,6))
print(matrixmul)
print(matrix.shape)

tensor([[0.2793, 0.8521, 0.3071, 0.7323, 0.8565, 0.9822],
        [0.6712, 1.1490, 0.5109, 1.3020, 0.9555, 1.6183]])
torch.Size([2, 2])


## Transpose Matrix
To Fix our tensor shape issues, we can manipulate the shape of one of our tensors using a `TRANSPOSE`

In [17]:
A=torch.rand(2,3)
B=torch.rand(2,3)
# print(A @ B) will not work cuz the inner dimension are not same
# we have to transpose any one of them
print(A)
print(A.T)
print(B)
print(B.T)
print(A.T @ B)
print(A @ B.T)

tensor([[0.9376, 0.3451, 0.8933],
        [0.0790, 0.2307, 0.0616]])
tensor([[0.9376, 0.0790],
        [0.3451, 0.2307],
        [0.8933, 0.0616]])
tensor([[0.8405, 0.2073, 0.8973],
        [0.1565, 0.2354, 0.5235]])
tensor([[0.8405, 0.1565],
        [0.2073, 0.2354],
        [0.8973, 0.5235]])
tensor([[0.8004, 0.2130, 0.8827],
        [0.3262, 0.1259, 0.4305],
        [0.7604, 0.1997, 0.8338]])
tensor([[1.6612, 0.6957],
        [0.1695, 0.0989]])


## Aggregations (min, max, mean, sum, argmin, argmax)

In [18]:
tensorA=torch.arange(10, 110, 10)
print(tensorA)
print(f"Minimum: {torch.min(tensorA)}")
print(f"Maximum: {torch.max(tensorA)}")
print(f"Mean: {torch.mean(tensorA.type(torch.float32))}")
# mean can calculated only for floating numbers
print(f"Sum: {torch.sum(tensorA)}")


tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
Minimum: 10
Maximum: 100
Mean: 55.0
Sum: 550


## Positional min, max and mean
##### Shows the `position` of the min or max value in the tensor

In [19]:
print(tensorA.argmin())
print(tensorA.argmax())
print(torch.argmin(tensorA))
print(torch.argmax(tensorA))
print(tensorA[0])
print(tensorA[9])

tensor(0)
tensor(9)
tensor(0)
tensor(9)
tensor(10)
tensor(100)


## Reshaping, Stacking, Squeezing, Unsqueezing, Permuting

`Reshaping` - reshapes the input tensor to a defined shape

`View` - return a view of an input tensor of certain shape but keep the same memory as the original tensor

`Stacking` - combine multiple tensors on top of eachother (vstack) or side by side (hstack)

`Squeezwe` - removes all one dimension from a tensor

`Unsqueeze` - adds a one dimension to a target tensor

In [20]:
#Reshaping
x=torch.arange(1, 11)
print(x, x.shape)
x_reshaped=x.reshape(1,10) # only works when (1*10 = actual x size)
print(x_reshaped, x_reshaped.shape)

#Viewing
z=x.view(1,10)
print(z,z.shape) # changing z changes x(bcuz a view of tensor shares the same memory as the original input)
z[:, 0]=5
print(z,x)

#Stacking
x_stacked=torch.stack([x,x,x,x],dim=0) #hstack
print(x_stacked)
x_stacked=torch.stack([x,x,x,x],dim=1) #vstack
print(x_stacked)

#Squeezing
print(f"Previous tensor and its shape: ",x_reshaped,x_reshaped.shape)
x_squeezed=x_reshaped.squeeze()
print(f"After removing extra dimensions from x_reshape: ",x_squeezed,x_squeezed.shape)

#Unsqueeze
print(f"Previous tensor and its shape: ",x_squeezed,x_squeezed.shape)
x_unsqueezed=x_squeezed.unsqueeze(dim=0) #need the dimension input to unsqeeze the tenor (adding the dimension)
print(f"After unsqueezing the squeesed tensor be like: ",x_unsqueezed,x_unsqueezed.shape)
x_unsqueezed=x_squeezed.unsqueeze(dim=1)
print(f"After unsqueezing the squeesed tensor be like: ",x_unsqueezed,x_unsqueezed.shape)

#Permute
x_og=torch.rand(size=(3,4,2)) #[height, width, colorchannel] 
print(x_og,x_og.shape)
x_permuted=x_og.permute(2,0,1) #shifting-->[height-->2, width-->0, colorchannel-->1]
print(x_permuted,x_permuted.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) torch.Size([10])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]) torch.Size([1, 10])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]) torch.Size([1, 10])
tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]) tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
tensor([[ 5,  5,  5,  5],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])
Previous tensor and its shape:  tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]) torch.Size([1, 10])
After removing extra dimensions from x_reshape:  tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]) torch.Size([10])
Previous ten

## Indexing (selectinhgdata from tensors)
indexing with Py Torch is similar to indexing with NumPy.

In [21]:
import torch
x= torch.arange(1,10).reshape(1,3,3)
print(x,x.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])


In [22]:
#lets index on our new tensors
print(x[0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [23]:
#lets index on the middle bracket (dim=1)
print(x[0][0])
#OR
print(x[0,0])

tensor([1, 2, 3])
tensor([1, 2, 3])


In [24]:
#lets index on the most inner bracket (last dimension)
print(x[0,0,0])
#OR
print(x[0][0][0])
print(x[0,1,1])

tensor(1)
tensor(1)
tensor(5)


In [25]:
print(x,x.shape)
#you can also use ":" to select "all" of a target dimension
print(x[:,0])
# get all values of 0th and 1st dimension but only index 1 of 2nd dimension
print(x[:,:,1])
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
print(x[:,1,1])
# get index 0 of the 0th and 1st dimension and all values of 2nd dimension
print(x[0,0,:])
# index on x to return 9
print(x[:,2,2])
# index on x to return 3,6,9
print(x[:,:,2])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3])
tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])
tensor([9])
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

Numpy is a popular scientific python numerical computing library.

And because of this, PyTorch has functionality to intereact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`

* PyTorch tensor -> Numpy -> `torch.tensor.numpy()`

In [26]:
# NumPy array from Tensor
import torch
import numpy as np
array=np.arange(1.0,8.0) #default dtype=float64
tensor=torch.from_numpy(array) #warning: when converting from numpy -> pytorch, pytorch reflects numpy's deafult datatype of float64 unless specified otherwise
print(array,tensor)

[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [27]:
#change the value of array, what will this do to 'tensor'?
array=array+1
print(array,tensor)
# hence changing the value of numpy dosnt affect the values of tensor

[2. 3. 4. 5. 6. 7. 8.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [28]:
# tensor to Numpy array
tensor=torch.ones(7) #default dtype=float32
numpy_tensor=tensor.numpy()
print(tensor, numpy_tensor, numpy_tensor.dtype)

tensor([1., 1., 1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1. 1. 1.] float32


In [29]:
#Change the tensor, what happens to 'numpy_tensor'?
tensor=tensor+1
print(tensor,numpy_tensor)
# hence changing the value of tensor dosnt affect the values of numpy_tensor


tensor([2., 2., 2., 2., 2., 2., 2.]) [1. 1. 1. 1. 1. 1. 1.]


## Reproducblity (trying to take random out of random

In short how a neural network learns:

`start with random numbers -> tensor operation -> update random numbers to try and make them better representation of the data -> again -> again -> again -> again...`

To REDUCE the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

In [30]:
import torch
random_tensorA=torch.rand(3,4)
random_tensorB=torch.rand(3,4)
print(random_tensorA)
print(random_tensorB)
print(random_tensorA==random_tensorB)

tensor([[0.9592, 0.1849, 0.1054, 0.7605],
        [0.2831, 0.7466, 0.8421, 0.4056],
        [0.2373, 0.4456, 0.5655, 0.3070]])
tensor([[0.4191, 0.7526, 0.3632, 0.7982],
        [0.4318, 0.3832, 0.4090, 0.2862],
        [0.2434, 0.8004, 0.9269, 0.5199]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [31]:
#lets make some randombut reproducible tensors
import torch
#set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED) #its works only 1 number of block when using in notebook
random_tensorC= torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensorD= torch.rand(3,4)
print(random_tensorC)
print(random_tensorD)
print(random_tensorC==random_tensorD)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs (and making faster computataions)

GPUs= faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working BTS

In [32]:
!nvidia-smi

Fri Sep 12 03:43:57 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 576.88                 Driver Version: 576.88         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   50C    P0              5W /   75W |      93MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [33]:
#Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [34]:
#Setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [35]:
#COUNT NUMBER OF GPUs
torch.cuda.device_count()

1

## Putting tensors (and/models) on the GPU
the reason we want our tensor/models on the GPU is bcuz using GPU results in faster computations

In [36]:
#create a tensor (default on the CPU)
tensor =torch.tensor([1,2,3])

#tensor not on GPU
print(tensor, tensor.device)

#Move tensor to GPU (if available)
tensor_on_gpu=tensor.to(device)
print(tensor_on_gpu)
# There is only 1 gpu in this device so the index of the gpu is '0'

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0')


### Numpy only works with cpu
Therefore we have to move tensors back to the CPU

In [39]:
#If tensors is on GPU, cant transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set the tensor to CPU
tensor_back_on_CPU=tensor_on_gpu.cpu().numpy()
print(tensor_back_on_CPU, tensor_back_on_CPU.device)
print(tensor_on_gpu)

[1 2 3] cpu
tensor([1, 2, 3], device='cuda:0')
