# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
import torch

tensorA=torch.rand(7,7)
tensorA
# Create random tensor


tensor([[0.0439, 0.0594, 0.8058, 0.3232, 0.6884, 0.7675, 0.8548],
        [0.7833, 0.5009, 0.0740, 0.8946, 0.5530, 0.5145, 0.2570],
        [0.9228, 0.8759, 0.0521, 0.3013, 0.4135, 0.2243, 0.8040],
        [0.6981, 0.9193, 0.7369, 0.5471, 0.4208, 0.3501, 0.9819],
        [0.3080, 0.9103, 0.6411, 0.8398, 0.7955, 0.0297, 0.2360],
        [0.4274, 0.3598, 0.4750, 0.5927, 0.7138, 0.1436, 0.1484],
        [0.0749, 0.5158, 0.4975, 0.4997, 0.0310, 0.5137, 0.5655]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensorB=torch.rand(1,7)
tensorA @ tensorB.T

# Perform matrix multiplication 


tensor([[2.4647],
        [2.3515],
        [2.3955],
        [2.8788],
        [2.2967],
        [1.7846],
        [1.6871]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED=0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
random_tensorC= torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
random_tensorD= torch.rand(1,7)

# Matrix multiply tensors
mm=random_tensorC @ random_tensorD.T
print(mm, mm.shape)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
RANDOM_seed=1234
torch.cuda.manual_seed(RANDOM_seed)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
RANDOM_SEED=1234

# Check for access to GPU
device="cuda" if torch.cuda.is_available() else "cuda"
print("Device: "+device)

# Create two random tensors on GPU
torch.manual_seed(RANDOM_SEED)
a=torch.rand(2,3).to(device)
torch.manual_seed(RANDOM_SEED)
b=torch.rand(2,3).to(device)
a, b


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
A=torch.matmul(a,b.T)
print(A, A.shape)

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [15]:
# Find max
print(A.max())
# Find min
print(A.min())


tensor(0.6287, device='cuda:0')
tensor(0.2161, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
print(A.argmax())

# Find arg min
print(A.argmin())

tensor(3, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
RANDOM_SEED=7

# Create random tensor
torch.manual_seed(RANDOM_SEED)
B=torch.rand(1,1,1,10)

# Remove single dimensions
B=B.squeeze()

# Print out tensors and their shapes
B, B.shape

(tensor([0.2837, 0.6567, 0.2388, 0.7313, 0.6012, 0.3043, 0.2548, 0.6294, 0.9665,
         0.7399]),
 torch.Size([10]))