# PyTorch Tensor Basics
This notebook explains different kinds of tensors in PyTorch — scalars, vectors, matrices, and higher-dimensional tensors — along with basic operations.

In [1]:
import torch

## Scalar
A scalar is a single number (0-dimensional tensor).
1. Structure.ndim - gives the number of dimension the structure have.
2. Structure.item - converts the type of the structure back to the python int.

In [2]:
scalar=torch.tensor(7)
print(scalar)
print(scalar.ndim) #no. of dimention does scalar have
print(scalar.item()) #Get tensor back as python int

tensor(7)
0
7


## Vector (1D tensor)
1. Structure.shape - gives the structure size

In [3]:
vector=torch.tensor([6,9])
print(vector)
print(vector.ndim)
print(vector[1])
print(vector.shape)

tensor([6, 9])
1
tensor(9)
torch.Size([2])


## Matrix (2D tensor)

In [4]:
matrix=torch.tensor([[7,8],
                     [9,10]])
print(matrix)
print(matrix.ndim)
print(matrix[1])
print(matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
tensor([ 9, 10])
torch.Size([2, 2])


## Tensor (3D example)

In [5]:
tensor=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [10,11,12]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [10, 11, 12]]])
3
torch.Size([1, 3, 3])


## Random Tensor
Creating a Random Tensor of size --> rows=3 and columns=4.

In [6]:
random_tensor=torch.rand(size=(3,4))
print(random_tensor)
print(random_tensor.ndim)

tensor([[0.5930, 0.3939, 0.5457, 0.7840],
        [0.6240, 0.7044, 0.5064, 0.4923],
        [0.5315, 0.9990, 0.4856, 0.7886]])
2


## Random tensor shaped like an image (Height, Width, Channels)

In [7]:
random_image_size_tensor=torch.rand(size=(224,224,3))
print(random_image_size_tensor.shape)
print(random_image_size_tensor.ndim)

torch.Size([224, 224, 3])
3


## Zeros and Ones

In [8]:
zeros=torch.zeros(size=(3,4))
print(zeros)
print(zeros*random_tensor)
ones=torch.ones(size=(3,4))
print(ones)
print(ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


## Creating ranges of tensors

In [9]:
zero_to_nine=torch.arange(0,10)
print(zero_to_nine)
one_to_ten=torch.arange(1,11)
print(one_to_ten)
one_to_thousand_with_50steps=torch.arange(start=1, end=1000, step=50)
print(one_to_thousand_with_50steps)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601, 651,
        701, 751, 801, 851, 901, 951])


## Creating tensor-like another tensor

In [10]:
one_to_ten=torch.zeros_like(input=one_to_ten)
print(one_to_ten)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


## Tensor Datatypes and Devices
**NOTE:** tensor datatypes is one of the 3 big errors you'll run into with pytorch & deep learning 
1. tensor not right datatype
2. tensor not right shape
3. tensor not on the right device

In [11]:
float32_tensor=torch.tensor([3.0, 6.0, 9.0],
                            dtype=None, #what data type is the tensor (default=float32)
                            device=None, #what device is your tensor on (default=None=cpu)
                            requires_grad=False) #whether or not to track gradiants with this tensor operation
print(float32_tensor)
print(float32_tensor.dtype)
float16_tensor=torch.tensor([2.0, 4.0, 6.0],
                            dtype=torch.float16,
                            device="cuda",
                            requires_grad=False)
print(float16_tensor)
print(float16_tensor.dtype)

tensor([3., 6., 9.])
torch.float32
tensor([2., 4., 6.], device='cuda:0', dtype=torch.float16)
torch.float16


## Type conversion

In [12]:
float16_tensor=float32_tensor.type(torch.float16)
print(float16_tensor)
print(float16_tensor*float32_tensor)
int_32_tensor=torch.tensor([2,3,4], dtype=torch.int32)
print(int_32_tensor)
print(float32_tensor*int_32_tensor)

tensor([3., 6., 9.], dtype=torch.float16)
tensor([ 9., 36., 81.])
tensor([2, 3, 4], dtype=torch.int32)
tensor([ 6., 18., 36.])


## Checking tensor attributes

In [13]:
some_tensor=torch.rand(3, 4)
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.5666, 0.5803, 0.3077, 0.2764],
        [0.8799, 0.7992, 0.7093, 0.5071],
        [0.7582, 0.3065, 0.1434, 0.1781]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Basic tensor operations (Addition, Subtraction, Multiplication, Division)

In [14]:
tensor=torch.tensor([1,2,3])
print(tensor+10)
print(tensor-10) #SLOW
print(tensor*10)
print(tensor/10)
#OR
print(torch.add(tensor, 10))
print(torch.sub(tensor, 10)) #FAST
print(torch.mul(tensor, 10))
print(torch.div(tensor, 10))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


## Matrix Multiplication
**NOTE:** There are 2 types of matrix multiplication:
1. Element wise multiplication.
2. Matrix multiplication (dot product).

In [15]:
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")
print(torch.matmul(tensor, tensor))
#OR
print(tensor @ tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
tensor(14)
tensor(14)


# 2 Rules
There are two main rules that performing matrix multiplication needs to satisfy:
### 1. Inner Dimension Should Match.
1. torch.Size([3, 2]) @ torch.Size([3, 4]) won't work'.
2. torch.Size([3, 2]) @ torch.Size([2, 5]) will work'.
3. torch.Size([2, 3]) @ torch.Size([3, 1]) will work'.
**NOTE:** In matrix A*B != B*A.
### 2. The resulting matrix has the shape of the Outer Dimension.

In [16]:
matrixmul=torch.matmul(torch.rand(2,3), torch.rand(3,6))
print(matrixmul)
print(matrix.shape)

tensor([[1.4268, 0.7305, 1.3250, 0.9002, 1.2727, 1.6670],
        [1.0518, 0.8206, 0.7554, 0.7349, 0.7816, 1.0639]])
torch.Size([2, 2])


# Transpose Matrix
To Fix our tensor shape issues, we can manipulate the shape of one of our tensors using a TRANSPOSE

In [21]:
A=torch.rand(2,3)
B=torch.rand(2,3)
# print(A @ B) will not work cuz the inner dimension are not same
# we have to transpose any one of them
print(A)
print(A.T)
print(B)
print(B.T)
print(A.T @ B)
print(A @ B.T)

tensor([[0.4665, 0.1836, 0.3292],
        [0.9140, 0.4906, 0.3933]])
tensor([[0.4665, 0.9140],
        [0.1836, 0.4906],
        [0.3292, 0.3933]])
tensor([[0.2887, 0.6602, 0.4189],
        [0.3984, 0.7172, 0.4774]])
tensor([[0.2887, 0.3984],
        [0.6602, 0.7172],
        [0.4189, 0.4774]])
tensor([[0.4988, 0.9635, 0.6317],
        [0.2485, 0.4731, 0.3111],
        [0.2517, 0.4994, 0.3257]])
tensor([[0.3937, 0.4746],
        [0.7525, 0.9038]])


## Aggregations (min, max, mean, sum, argmin, argmax)

In [22]:
tensorA=torch.arange(10, 110, 10)
print(tensorA)
print(f"Minimum: {torch.min(tensorA)}")
print(f"Maximum: {torch.max(tensorA)}")
print(f"Mean: {torch.mean(tensorA.type(torch.float32))}")
# mean can calculated only for floating numbers
print(f"Sum: {torch.sum(tensorA)}")


tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
Minimum: 10
Maximum: 100
Mean: 55.0
Sum: 550


## Positional min, max and mean
##### Shows the position of the min or max value in the tensor

In [23]:
print(tensorA.argmin())
print(tensorA.argmax())
print(torch.argmin(tensorA))
print(torch.argmax(tensorA))
print(tensorA[0])
print(tensorA[9])

tensor(0)
tensor(9)
tensor(0)
tensor(9)
tensor(10)
tensor(100)


## Reshaping, Stacking, Squeezing, Unsqueezing, Permuting
#### 1) Reshaping - reshapes the input tensor to a defined shape
#### 2) View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
#### 3) Stacking - combine multiple tensors on top of eachother (vstack) or side by side (hstack)
#### 4) Squeezwe - removes all one dimension from a tensor
#### 5) Unsqueeze - adds a one dimension to a target tensor

In [24]:
#Reshaping
x=torch.arange(1, 11)
print(x, x.shape)
x_reshaped=x.reshape(1,10) # only works when (1*10 = actual x size)
print(x_reshaped, x_reshaped.shape)

#Viewing
z=x.view(1,10)
print(z,z.shape) # changing z changes x(bcuz a view of tensor shares the same memory as the original input)
z[:, 0]=5
print(z,x)

#Stacking
x_stacked=torch.stack([x,x,x,x],dim=0) #hstack
print(x_stacked)
x_stacked=torch.stack([x,x,x,x],dim=1) #vstack
print(x_stacked)

#Squeezing
print(f"Previous tensor and its shape: ",x_reshaped,x_reshaped.shape)
x_squeezed=x_reshaped.squeeze()
print(f"After removing extra dimensions from x_reshape: ",x_squeezed,x_squeezed.shape)

#Unsqueeze
print(f"Previous tensor and its shape: ",x_squeezed,x_squeezed.shape)
x_unsqueezed=x_squeezed.unsqueeze(dim=0) #need the dimension input to unsqeeze the tenor (adding the dimension)
print(f"After unsqueezing the squeesed tensor be like: ",x_unsqueezed,x_unsqueezed.shape)
x_unsqueezed=x_squeezed.unsqueeze(dim=1)
print(f"After unsqueezing the squeesed tensor be like: ",x_unsqueezed,x_unsqueezed.shape)

#Permute
x_og=torch.rand(size=(3,4,2)) #[height, width, colorchannel] 
print(x_og,x_og.shape)
x_permuted=x_og.permute(2,0,1) #shifting-->[height-->2, width-->0, colorchannel-->1]
print(x_permuted,x_permuted.shape)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) torch.Size([10])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]) torch.Size([1, 10])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]) torch.Size([1, 10])
tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]) tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
tensor([[ 5,  5,  5,  5],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])
Previous tensor and its shape:  tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]) torch.Size([1, 10])
After removing extra dimensions from x_reshape:  tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]) torch.Size([10])
Previous ten